### ISSUE TITLE
Missing "Invalid amount" validation

### ISSUE THREAD

**Issue by kostovster** [nolus-protocol/webapp#43]
When entering an invalid amount for a transfer in the subsection #receive, the system does not display the message "Invalid amount", similar to the subsection #send

![Image](https://github.com/nolus-protocol/webapp/assets/95979747/032b899a-1c2b-4e2d-9683-edbc59d10b87)

![Image](https://github.com/nolus-protocol/webapp/assets/95979747/aa02d09b-aac1-4be6-8d2c-75e52e863f3f)

**Comment by pKarlovska** [comment]
When the balance is 0.000000, a system error "Invalid amount" is displayed. However, when entering the amount 0.00000022, the "Invalid amount" message disappears, allowing the transaction to be confirmed.


![Image](https://github.com/nolus-protocol/webapp/assets/95979747/63883f28-24c7-430c-bea3-217ba8a4f341)
